name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install --triplet x64-windows-static

      - name: Configure
        run: |
          cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Install
        run: cmake --install build --config Release --prefix install

      - name: Prepare archive
        run: |
          Rename-Item install altman

      - name: Package
        run: Compress-Archive -Path altman -DestinationPath altman.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: altman.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
